# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];


  time.timeZone = "America/Los_Angeles";
  networking.hostName = "nixos";
  networking.networkmanager.enable = true;
  services.blueman.enable = true;
  powerManagement.cpuFreqGovernor = "performance"; # Default governor, overridden by power-profiles-daemon
  users.users.ryan.extraGroups = [ "wheel" "networkmanager" ];
  hardware.bluetooth.powerOnBoot = true;
  hardware.enableRedistributableFirmware = true;

    # Enable Mesa drivers (stable for now to avoid instability)
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    package = pkgs.mesa;  # Stable Mesa
    extraPackages = with pkgs; [
      libva-vdpau-driver  # Video acceleration
      libvdpau-va-gl  # VDPAU driver
      rocmPackages.clr.icd  # OpenCL support for AMD
    ];
  };

  boot.loader.grub = {
    enable = true;
    configurationLimit = 20;
    efiInstallAsRemovable = true;
    devices = ["nodev"];
    efiSupport = true;
    fsIdentifier = "uuid";
  };
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [ 
    "amdgpu.abmlevel=0"
    "amdgpu.sg_display=0"
    "amdgpu.exp_hw_support=1"
    "amdgpu.dcdebugmask=0x410"
  ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "amdgpu" "v4l2loopback" "kvm-amd"];
  boot.extraModulePackages = [ config.boot.kernelPackages.v4l2loopback ];
  boot.extraModprobeConfig = ''
    options v4l2loopback devices=1 video_nr=10 card_label="Virtual Cam" exclusive_caps=1
  '';

    fileSystems."/" =
    { device = "/dev/disk/by-uuid/c41975b7-877f-47fe-ad34-b6516fb1dfff";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9107-6145";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6ec4f9ce-6726-4cc5-94da-32272579d271"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;
  nixpkgs.config.allowUnfree = true;
  nixpkgs.config.permittedInsecurePackages = [
    "qtwebengine-5.15.19"
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
